using System;
using System.IO;
using System.Linq;
using System.Text;
using Fuxion.Tools.Core.Versioning;

namespace Fuxion.Tools.Core.StaticMetadata;

public sealed record StaticMetadataRequest(
	string OutputPath,
	string ProjectName,
	string Namespace,
	VersionProps? VersionProps,
	string BuildDateUtc,
	string? Branch,
	string? Commit,
	string? OriginUrlSHA256,
	string? FirstCommit,
	string? TargetFramework,
	string? Configuration
);

public static class StaticMetadataFileGenerator
{
	public static string GetClassName(string projectName)
	{
		if (string.IsNullOrWhiteSpace(projectName))
			return "Project";

		var chars = projectName
			.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_')
			.ToArray();
		if (chars.Length == 0)
			return "Project";
		if (!char.IsLetter(chars[0]) && chars[0] != '_')
			return "_" + new string(chars);
		return new(chars);
	}

	public static bool Generate(StaticMetadataRequest request)
	{
		ArgumentException.ThrowIfNullOrWhiteSpace(request.OutputPath);
		ArgumentException.ThrowIfNullOrWhiteSpace(request.ProjectName);
		ArgumentException.ThrowIfNullOrWhiteSpace(request.Namespace);

		var className = GetClassName(request.ProjectName);
		var content = BuildSource(className, request);
		return WriteIfChanged(request.OutputPath, content);
	}

	public static bool DeleteIfExists(string outputPath)
	{
		if (string.IsNullOrWhiteSpace(outputPath) || !File.Exists(outputPath))
			return false;
		File.Delete(outputPath);
		return true;
	}

	private static string BuildSource(string className, StaticMetadataRequest request)
	{
		var b = new StringBuilder();

		// HEADER
		b.AppendLine($$"""
			// ========================================================================
			// This file is auto-generated by Fuxion.Tools.Sdk. Do not edit manually.
			// Target Framework Symbol: {{GetTargetFrameworkSymbol(request.TargetFramework)}}
			// ========================================================================
			namespace {{request.Namespace}}.{{className}}
			{
			""");

		// PROJECT
		b.AppendLine($$"""
				/// <summary>
				/// Static metadata about the project, such as its name. This information is generated at build time and can be used for various purposes, such as logging, diagnostics, or displaying in the application.
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCode("Fuxion.Tools", null)]
				public static partial class Project
				{
					/// <summary>
					/// The name of the project. This is generated at build time based on the ProjectName property of the build request, and can be used for various purposes, such as logging, diagnostics, or displaying in the application. The value is a string that represents the name of the project. Note that this value is generated at build time, so it will reflect the name of the project for which the build was performed, not necessarily the name of the currently running application (if different).
					/// </summary>
					public static readonly string Name = "{{Escape(request.ProjectName)}}";
				}
			""");

		// BUILD (target, config, date, CI, packing)
		b.AppendLine($$"""
				/// <summary>
				/// Static metadata about the build, such as target framework, configuration, build date, whether it's a CI build or a packing build. This information is generated at build time and can be used for various purposes, such as logging, diagnostics, or displaying in the application.
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCode("Fuxion.Tools", null)]
				public static partial class Build
				{
					/// <summary>
					/// The target framework for which the project is being built. This is generated at build time based on the TargetFramework property of the build request, and can be used for various purposes, such as logging, diagnostics, or displaying in the application. The value is a string that represents the target framework, such as "netstandard2.0", "net472", "net8.0", "net9.0", or "net10.0". Note that this value is generated at build time, so it will reflect the target framework for which the project is being built, not necessarily the target framework of the currently running application (if different).
					/// </summary>
					public static readonly string TargetFramework = "{{Escape(request.TargetFramework)}}";
					/// <summary>
					/// The build configuration for which the project is being built. This is generated at build time based on the Configuration property of the build request, and can be used for various purposes, such as logging, diagnostics, or displaying in the application. The value is a string that represents the build configuration, such as "Debug" or "Release". Note that this value is generated at build time, so it will reflect the build configuration for which the project is being built, not necessarily the build configuration of the currently running application (if different).
					/// </summary>
					public static readonly string Configuration = "{{Escape(request.Configuration)}}";
					/// <summary>
					/// The UTC date and time when the build was performed. This is generated at build time using the current UTC date and time, and can be used for various purposes, such as logging, diagnostics, or displaying in the application. The value is represented as a DateTimeOffset to include both the date and time along with the offset from UTC (which is zero in this case). Note that this value is generated at build time, so it will reflect the time when the build was performed, not necessarily the time when the application is running.
					/// </summary>
					public static readonly global::System.DateTime BuildDateUtc = new global::System.DateTime({{ParseBuildDate(request.BuildDateUtc).Ticks}}L, global::System.DateTimeKind.Utc);
					/// <summary>
					/// Gets the assembly of the build class. This can be useful for scenarios where you want to access assembly-level attributes or metadata related to the build. The Assembly property returns the assembly that contains the Build class, which is the assembly generated for this static metadata. Note that this assembly will contain the static metadata for the build, and may not necessarily be the same as the assembly of the currently running application (if different).
					/// </summary>
					public static global::System.Reflection.Assembly Assembly => typeof(Build).Assembly;
				}
			""");

		// VERSIONING (pendiente)
		if (request.VersionProps is not null)
			b.AppendLine($$"""
					/// <summary>
					/// Static metadata about the versioning of the project, such as version number, package version, assembly version, file version, informational version, and fingerprint. This information is generated at build time based on the provided VersionProps and can be used for various purposes, such as logging, diagnostics, or displaying in the application.
					/// </summary>
					[global::System.CodeDom.Compiler.GeneratedCode("Fuxion.Tools", null)]
					public static partial class Versioning
					{
						/// <summary>
						/// The version number of the project. This is generated at build time based on the Version property of the VersionProps provided in the build request, and can be used for various purposes, such as logging, diagnostics, or displaying in the application. The value is a string that represents the version number, such as "1.0.0". Note that this value is generated at build time, so it will reflect the version number for which the project was built, not necessarily the version number of the currently running application (if different).
						/// </summary>
						public static readonly string Version = "{{Escape(request.VersionProps.Version)}}";
						/// <summary>
						/// The package version of the project. This is generated at build time based on the PackageVersion property of the VersionProps provided in the build request, and can be used for various purposes, such as logging, diagnostics, or displaying in the application. The value is a string that represents the package version, such as "1.0.0". Note that this value is generated at build time, so it will reflect the package version for which the project was built, not necessarily the package version of the currently running application (if different).
						/// </summary>
						public static readonly string PackageVersion = "{{Escape(request.VersionProps.PackageVersion)}}";
						/// <summary>
						/// The assembly version of the project. This is generated at build time based on the AssemblyVersion property of the VersionProps provided in the build request, and can be used for various purposes, such as logging, diagnostics, or displaying in the application. The value is a string that represents the assembly version, such as "
						/// </summary>
						public static readonly string AssemblyVersion = "{{Escape(request.VersionProps.AssemblyVersion)}}";
						/// <summary>
						/// The file version of the project. This is generated at build time based on the FileVersion property of the VersionProps provided in the build request, and can be used for various purposes, such as logging, diagnostics, or displaying in the application. The value is a string that represents the file version, such as "1.0.0". Note that this value is generated at build time, so it will reflect the file version for which the project was built, not necessarily the file version of the currently running application (if different).
						/// </summary>
						public static readonly string FileVersion = "{{Escape(request.VersionProps.FileVersion)}}";
						/// <summary>
						/// The informational version of the project. This is generated at build time based on the InformationalVersion property of the VersionProps provided in the build request, and can be used for various purposes, such as logging, diagnostics, or displaying in the application. The value is a string that represents the informational version, which can include additional information such as pre-release labels or build metadata (e.g., "1.0.0-beta+exp.sha.5114f85"). Note that this value is generated at build time, so it will reflect the informational version for which the project was built, not necessarily the informational version of the currently running application (if different).
						/// </summary>
						public static readonly string InformationalVersion = "{{Escape(request.VersionProps.InformationalVersion)}}";
					}
				""");
		// REPOSITORY
		b.AppendLine($$"""
				/// <summary>
				/// Static metadata about the repository, such as branch name, commit hash, origin URL hash, first commit and repository path. This information is generated at build time and can be used for various purposes, such as logging, diagnostics, or displaying in the application.
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCode("Fuxion.Tools", null)]
				public static partial class Repository
				{
					/// <summary>
					/// The name of the branch from which the project was built. This is generated at build time based on the Branch property of the build request, and can be used for various purposes, such as logging, diagnostics, or displaying in the application. The value is a string that represents the name of the branch, such as "main" or "develop". Note that this value is generated at build time, so it will reflect the branch from which the project was built, not necessarily the branch of the currently running application (if different).
					/// </summary>
					public static readonly string Branch = "{{Escape(request.Branch)}}";
					/// <summary>
					/// The commit hash from which the project was built. This is generated at build time based on the Commit property of the build request, and can be used for various purposes, such as logging, diagnostics, or displaying in the application. The value is a string that represents the commit hash, such as "a1b2c3d4". Note that this value is generated at build time, so it will reflect the commit from which the project was built, not necessarily the commit of the currently running application (if different).
					/// </summary>
					public static readonly string Commit = "{{Escape(request.Commit)}}";
					/// <summary>
					/// SHA-256 hash of normalized remote origin URL.
					/// </summary>
					public static readonly string OriginUrlSHA256 = "{{Escape(request.OriginUrlSHA256)}}";
					/// <summary>
					/// First commit SHA reachable in repository history.
					/// </summary>
					public static readonly string FirstCommit = "{{Escape(request.FirstCommit)}}";
				}
			""");

		b.AppendLine(""""
				/// <summary>
				/// Provides a method to get all the static metadata as a JsonElement. This can be useful for scenarios where you want to serialize the metadata to JSON or work with it in a structured way. The GetJsonElement method will return a JsonElement that contains all the metadata properties organized in a hierarchical structure. Note that the JsonElement is cached after the first generation, so subsequent calls to GetJsonElement will return the cached value for better performance.
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCode("Fuxion.Tools", null)]
				public static class Json
				{
						/// <summary>
						/// A string representation of the static metadata in JSON format. This is generated at build time using string interpolation to create a JSON string that contains all the metadata properties organized in a hierarchical structure. The JSON structure will have the following format:
						/// </summary>
						public static readonly string JsonString = $$"""
						{
							"Project": {
								"Name": "{{Project.Name}}"
							},
							"Build": {
								"TargetFramework": "{{Build.TargetFramework}}",
								"Configuration": "{{Build.Configuration}}",
								"BuildDateUtc": "{{Build.BuildDateUtc:O}}"
							},
			__VERSIONING__				"Repository": {
								"Branch": "{{Repository.Branch}}",
								"Commit": "{{Repository.Commit}}",
								"OriginUrlSHA256": "{{Repository.OriginUrlSHA256}}",
								"FirstCommit": "{{Repository.FirstCommit}}"
							}
						}
						""";
				}
			"""".Replace("__VERSIONING__", request.VersionProps is null ? "" : VersioningJson, StringComparison.Ordinal));

		// FOOTER
		b.AppendLine("""
			}
			""");

		return b.ToString();
	}

	// The Versioning section of the JSON, only when there is a version: without it the Json class referenced a
	// Versioning class that was not generated (a KNOWN BUG of K2.1, fixed in K3.2).
	const string VersioningJson = """
					"Versioning": {
						"Version": "{{Versioning.Version}}",
						"PackageVersion": "{{Versioning.PackageVersion}}",
						"AssemblyVersion": "{{Versioning.AssemblyVersion}}",
						"FileVersion": "{{Versioning.FileVersion}}",
						"InformationalVersion": "{{Versioning.InformationalVersion}}"
					},

	""";

	// The build date comes from the request (the caller decides: SOURCE_DATE_EPOCH, the commit date…), so the same
	// inputs give the same file and it is not rewritten on every build (a KNOWN BUG of K2.1, fixed in K3.2).
	static DateTime ParseBuildDate(string value)
		=> DateTimeOffset.Parse(value, System.Globalization.CultureInfo.InvariantCulture,
			System.Globalization.DateTimeStyles.AssumeUniversal | System.Globalization.DateTimeStyles.AdjustToUniversal).UtcDateTime;

	private static string? GetTargetFrameworkSymbol(string? targetFramework)
	{
		if (string.IsNullOrWhiteSpace(targetFramework))
			return null;

		var baseTfm = targetFramework.Split('-', 2)[0].Trim();
		if (baseTfm.Length == 0)
			return null;

		return baseTfm
			.Replace('.', '_')
			.Replace('-', '_')
			.ToUpperInvariant();
	}

	private static bool WriteIfChanged(string path, string content)
	{
		var dir = Path.GetDirectoryName(path);
		if (!string.IsNullOrWhiteSpace(dir))
			Directory.CreateDirectory(dir);

		if (File.Exists(path))
		{
			var current = File.ReadAllText(path);
			if (string.Equals(current, content, StringComparison.Ordinal))
				return false;
		}

		File.WriteAllText(path, content, new UTF8Encoding(false));
		return true;
	}

	private static string Escape(string? value)
	{
		return (value ?? string.Empty).Replace("\\", "\\\\", StringComparison.Ordinal)
			.Replace("\"", "\\\"", StringComparison.Ordinal);
	}
}