using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Fuxion.Tools.Core.Diagnostics;
using Fuxion.Tools.Core.Dotnet;

namespace Fuxion.Tools.Core.Workspace;

/// <summary>
/// The workspace's <c>_fx/dotnet.yaml</c> and the files its imports use (<c>_fx/dotnet/</c>), copied to each mounted .NET
/// repository (one with a <c>global.json</c> at its root) as <c>_fx/.workspace/</c>, like the skills and the rules
/// (design §7.3, plan N decision 15). Each repository gets the files its tags make apply; the copy of the yaml keeps
/// those tags (<see cref="DotnetModule.TagsMark"/>) so a clone outside the workspace generates the same. Then each
/// repository's generated files are brought up to date (<c>fx sync dotnet</c>). The copies are versioned in the
/// repositories and carry the GENERATED header (D-11); copies the workspace no longer gives are removed.
/// </summary>
public static class DotnetPropagation
{
	public const string MissingImport = "workspace.missing-import";
	public const string InvalidConfig = "workspace.invalid-dotnet";
	const string Folder = ".workspace";

	public static void Run(WorkspaceManifest manifest, IReadOnlyList<WorkspaceRepository> mounted, bool write, bool doctor,
		List<SyncFile> files, List<FxDiagnostic> diagnostics)
	{
		var source = Path.Combine(manifest.Root, "_fx", "dotnet.yaml");
		if (!File.Exists(source))
			return;
		DotnetConfig config;
		try
		{
			config = DotnetYamlReader.ReadFile(source);
		}
		catch (DotnetConfigException ex)
		{
			diagnostics.AddRange(ex.Diagnostics.Select(d => d with { Code = InvalidConfig, File = "_fx/dotnet.yaml" }));
			return;
		}
		var yaml = File.ReadAllText(source).Replace("\r\n", "\n");

		foreach (var repo in mounted)
		{
			var repoRoot = manifest.FullPath(repo);
			if (!File.Exists(Path.Combine(repoRoot, "global.json")))
				continue;
			var prefix = repo.Path.TrimEnd('/') + "/_fx/" + Folder + "/";
			var tags = repo.Tags ?? [];
			var applies = config.ForTags(tags);

			// The yaml, whole, with the repo's tags; and the files of the imports that apply to it
			var expected = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "dotnet.yaml" };
			WorkspaceModule.Generate(manifest.Root, prefix + "dotnet.yaml",
				"# GENERATED by fx from the workspace's _fx/dotnet.yaml. DO NOT EDIT. Regenerate with: fx sync workspace\n" +
				$"{DotnetModule.TagsMark} {string.Join(", ", tags)}\n" + yaml,
				"#", write, adopt: false, files, diagnostics);
			foreach (var file in applies.Imports.SelectMany(i => i.Props.Concat(i.Targets)).Distinct(StringComparer.OrdinalIgnoreCase))
			{
				var from = Path.Combine(manifest.Root, "_fx", file);
				if (!File.Exists(from))
				{
					diagnostics.Add(FxDiagnostic.Error(MissingImport, $"dotnet.yaml imports _fx/{file}, which does not exist.", "_fx/dotnet.yaml"));
					continue;
				}
				expected.Add(file);
				WorkspaceModule.Generate(manifest.Root, prefix + file, WithHeader(File.ReadAllText(from).Replace("\r\n", "\n"), file),
					"<!--", write, adopt: false, files, diagnostics);
			}

			// What the workspace no longer gives (only fx's files)
			var folder = Path.Combine(repoRoot, "_fx", Folder);
			if (Directory.Exists(folder))
				foreach (var path in Directory.EnumerateFiles(folder, "*", SearchOption.AllDirectories))
				{
					var relative = Path.GetRelativePath(folder, path).Replace('\\', '/');
					if (expected.Contains(relative) || !File.ReadAllText(path).Contains("GENERATED by fx", StringComparison.Ordinal))
						continue;
					if (write)
						File.Delete(path);
					files.Add(new(prefix + relative, write ? SyncFileStatus.Written : SyncFileStatus.WouldWrite));
				}

			// The repo's generated files, from the copy (in a dry run, from what is there)
			if (!DotnetModule.Applies(repoRoot))
				continue;
			var result = doctor ? DotnetModule.Doctor(repoRoot) : DotnetModule.Sync(repoRoot, dryRun: !write);
			files.AddRange(result.Files.Select(f => f with { Path = repo.Path.TrimEnd('/') + "/" + f.Path }));
			diagnostics.AddRange(result.Diagnostics.Select(d => d with { File = d.File is null ? repo.Path : repo.Path.TrimEnd('/') + "/" + d.File }));
		}
	}

	// The GENERATED header as an XML comment: first, or after the XML declaration if the file has one
	static string WithHeader(string text, string file)
	{
		var header = $"<!-- GENERATED by fx from the workspace's _fx/{file}. DO NOT EDIT. Regenerate with: fx sync workspace -->\n";
		if (!text.StartsWith("<?xml", StringComparison.Ordinal))
			return header + text;
		var end = text.IndexOf('\n') + 1;
		return end == 0 ? text + "\n" + header : text[..end] + header + text[end..];
	}
}
