using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Fuxion.Tools.Core.Diagnostics;

namespace Fuxion.Tools.Core.Workspace;

/// <summary>
/// The workspace solution (<c>Fuxion.slnx</c>, design §4.3, D-33): the solution of every mounted repository, in the
/// order of the manifest, with its paths from the workspace root and its folders under <c>/&lt;repo&gt;/</c>; a project
/// another repository already brought is not repeated, and <c>solutionExclude</c> leaves out what a repo wants out.
/// </summary>
public static class SolutionGenerator
{
	public const string HeaderMark = "GENERATED by fx";
	public const string FileName = "Fuxion.slnx";
	public const string MissingSolution = "workspace.missing-solution";

	public static string Generate(WorkspaceManifest manifest, IEnumerable<WorkspaceRepository> mounted, List<FxDiagnostic> diagnostics)
	{
		var root = manifest.Root;
		var platforms = new List<string>();
		var buildTypes = new List<string>();
		var folders = new List<(string Name, List<XElement> Items)>();
		var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

		List<XElement> Folder(string name)
		{
			var folder = folders.FirstOrDefault(f => string.Equals(f.Name, name, StringComparison.OrdinalIgnoreCase));
			if (folder.Items is null)
			{
				folder = (name, []);
				folders.Add(folder);
			}
			return folder.Items;
		}

		// The workspace's own files
		var workspaceItems = Folder("/.workspace/");
		foreach (var file in new[] { "_fx/workspace.yaml", "global.json", "CLAUDE.md", "README.md" })
			if (File.Exists(Path.Combine(root, file)))
				workspaceItems.Add(new XElement("File", new XAttribute("Path", file)));

		foreach (var repo in mounted.Where(r => r.Solution is not null))
		{
			var repoRoot = manifest.FullPath(repo);
			var solutionPath = Path.GetFullPath(Path.Combine(repoRoot, repo.Solution!));
			if (!File.Exists(solutionPath))
			{
				diagnostics.Add(FxDiagnostic.Warning(MissingSolution, $"Repository '{repo.Name}': its solution '{repo.Solution}' does not exist; it is left out.", WorkspaceManifest.RelativePath, repo.Line));
				continue;
			}
			var solutionDir = Path.GetDirectoryName(solutionPath)!;
			var solution = XDocument.Load(solutionPath).Root!;

			foreach (var platform in solution.Elements("Configurations").Elements("Platform").Select(p => (string?)p.Attribute("Name")).OfType<string>())
				if (!platforms.Contains(platform, StringComparer.OrdinalIgnoreCase))
					platforms.Add(platform);
			foreach (var buildType in solution.Elements("Configurations").Elements("BuildType").Select(p => (string?)p.Attribute("Name")).OfType<string>())
				if (!buildTypes.Contains(buildType, StringComparer.OrdinalIgnoreCase))
					buildTypes.Add(buildType);

			void Add(XElement item, string folderName)
			{
				if ((string?)item.Attribute("Path") is not { } path)
					return;
				var full = Path.GetFullPath(Path.Combine(solutionDir, path));
				var fromRepo = Path.GetRelativePath(repoRoot, full).Replace('\\', '/');
				if ((repo.SolutionExclude ?? []).Any(e => fromRepo.StartsWith(e.TrimEnd('/') + "/", StringComparison.OrdinalIgnoreCase) || string.Equals(fromRepo, e, StringComparison.OrdinalIgnoreCase)))
					return;
				if (!seen.Add(full))
					return;
				var copy = new XElement(item);
				copy.SetAttributeValue("Path", Path.GetRelativePath(root, full).Replace('\\', '/'));
				Folder(folderName).Add(copy);
			}

			foreach (var item in solution.Elements().Where(e => e.Name.LocalName is "Project" or "File"))
				Add(item, $"/{repo.Name}/");
			foreach (var folder in solution.Elements("Folder"))
			{
				var name = ((string?)folder.Attribute("Name") ?? "/").Trim('/');
				var folderName = name.Length == 0 ? $"/{repo.Name}/" : $"/{repo.Name}/{name}/";
				var items = folder.Elements().Where(e => e.Name.LocalName is "Project" or "File").ToList();
				// an empty folder of the solution stays; one whose items were all excluded goes
				if (items.Count == 0)
					Folder(folderName);
				foreach (var item in items)
					Add(item, folderName);
			}
		}

		// every parent folder is declared too (/plus/ and /plus/next/ for /plus/next/src/)
		foreach (var name in folders.Select(f => f.Name).ToList())
		{
			var parts = name.Trim('/').Split('/');
			for (var i = 1; i < parts.Length; i++)
				Folder("/" + string.Join('/', parts.Take(i)) + "/");
		}

		var b = new StringBuilder();
		b.Append("<Solution>\n");
		b.Append($"  <!-- {HeaderMark} from _fx/workspace.yaml and the solutions of the mounted repositories. DO NOT EDIT. Regenerate with: fx sync workspace -->\n");
		if (platforms.Count > 0 || buildTypes.Count > 0)
		{
			b.Append("  <Configurations>\n");
			foreach (var buildType in buildTypes)
				b.Append($"    <BuildType Name=\"{buildType}\" />\n");
			foreach (var platform in platforms)
				b.Append($"    <Platform Name=\"{platform}\" />\n");
			b.Append("  </Configurations>\n");
		}
		// parent folders before their children, each level in order
		foreach (var (name, items) in folders.OrderBy(f => f.Name == "/.workspace/" ? 0 : 1).ThenBy(f => f.Name, StringComparer.Ordinal))
		{
			if (items.Count == 0)
			{
				b.Append($"  <Folder Name=\"{name}\" />\n");
				continue;
			}
			b.Append($"  <Folder Name=\"{name}\">\n");
			foreach (var item in items.OrderBy(i => i.Name.LocalName == "File" ? 0 : 1).ThenBy(i => (string?)i.Attribute("Path"), StringComparer.OrdinalIgnoreCase))
				b.Append("    ").Append(item.ToString(SaveOptions.DisableFormatting)).Append('\n');
			b.Append("  </Folder>\n");
		}
		b.Append("</Solution>\n");
		return b.ToString();
	}
}
