using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using System.Xml.Linq;
using Fuxion.Tools.Core.Diagnostics;

namespace Fuxion.Tools.Core.Workspace;

/// <summary>
/// <c>_fx/~$workspace.props</c> (design §6): the map Fuxion.Tools.Sdk uses to resolve <c>FuxionReference</c>. For each
/// project of the solutions of the mounted repositories (named by its file, like the package): a
/// <c>FuxionWorkspaceProject</c> item, and a <c>ProjectReference</c> built from the <c>FuxionReference</c> with that name,
/// so it keeps its metadata. Local (<c>~$</c>), generated.
/// </summary>
public static class WorkspacePropsGenerator
{
	public const string FileName = "_fx/~$workspace.props";
	public const string DuplicateProject = "workspace.duplicate-project";

	public static string Generate(WorkspaceManifest manifest, IEnumerable<WorkspaceRepository> mounted, List<FxDiagnostic> diagnostics)
	{
		var b = new StringBuilder();
		b.Append("<!-- GENERATED by fx from _fx/workspace.yaml and the solutions of the mounted repositories. DO NOT EDIT. Regenerate with: fx sync workspace -->\n");
		b.Append("<Project>\n");
		b.Append("\t<ItemGroup>\n");
		foreach (var (name, (path, repository)) in Projects(manifest, mounted, diagnostics).OrderBy(p => p.Key, StringComparer.OrdinalIgnoreCase))
		{
			var n = SecurityElement.Escape(name);
			var p = SecurityElement.Escape(path);
			b.Append($"\t\t<FuxionWorkspaceProject Include=\"{n}\" Repository=\"{repository}\" Path=\"{p}\" />\n");
			b.Append($"\t\t<ProjectReference Include=\"@(FuxionReference->WithMetadataValue('Identity', '{n}')->'{p}')\" />\n");
		}
		b.Append("\t</ItemGroup>\n");
		b.Append("</Project>\n");
		return b.ToString();
	}

	/// <summary>
	/// The projects of the solutions of the mounted repositories, by name (the file name, like the package id; without
	/// case): full path and repository. The first repository of the manifest that brings a name wins, with a warning.
	/// </summary>
	public static Dictionary<string, (string Path, string Repository)> Projects(WorkspaceManifest manifest, IEnumerable<WorkspaceRepository> mounted, List<FxDiagnostic> diagnostics)
	{
		var projects = new Dictionary<string, (string Path, string Repository)>(StringComparer.OrdinalIgnoreCase);
		foreach (var repo in mounted.Where(r => r.Solution is not null))
		{
			var repoRoot = manifest.FullPath(repo);
			var solutionPath = Path.GetFullPath(Path.Combine(repoRoot, repo.Solution!));
			if (!File.Exists(solutionPath))
				continue;
			var solutionDir = Path.GetDirectoryName(solutionPath)!;
			foreach (var project in XDocument.Load(solutionPath).Descendants("Project").Select(p => (string?)p.Attribute("Path")).OfType<string>())
			{
				var full = Path.GetFullPath(Path.Combine(solutionDir, project));
				var fromRepo = Path.GetRelativePath(repoRoot, full).Replace('\\', '/');
				if ((repo.SolutionExclude ?? []).Any(e => fromRepo.StartsWith(e.TrimEnd('/') + "/", StringComparison.OrdinalIgnoreCase)))
					continue;
				var name = Path.GetFileNameWithoutExtension(full);
				if (projects.TryGetValue(name, out var existing))
				{
					if (!string.Equals(existing.Path, full, StringComparison.OrdinalIgnoreCase))
						diagnostics.Add(FxDiagnostic.Warning(DuplicateProject,
							$"Project '{name}' is in '{existing.Repository}' and in '{repo.Name}': FuxionReference uses the one of '{existing.Repository}'."));
					continue;
				}
				projects[name] = (full, repo.Name);
			}
		}
		return projects;
	}
}
