using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Text;

namespace Fuxion.Tools.Core.Dotnet;

/// <summary>
/// What <c>fx sync dotnet</c> writes in a repo's <c>_fx/</c> (design §7.3): <c>dotnet.g.props</c> (the <c>value</c>
/// variables and the <c>props:</c> imports), <c>dotnet.g.targets</c> (the <c>when</c> variables, their constants and the
/// <c>targets:</c> imports) and <c>packages.g.props</c> (a <c>PackageVersion</c>
/// per id and version). Text with '\n'; every file starts with the GENERATED header (D-11).
/// </summary>
public static class DotnetGenerator
{
	public const string HeaderMark = "GENERATED by fx";

	public static string Header(string sources) => $"<!-- {HeaderMark} from {sources}. DO NOT EDIT. Regenerate with: fx sync dotnet -->";

	/// <param name="imports">The props: imports: path relative to <c>_fx/</c> and expanded condition (null: always).</param>
	public static string Props(DotnetConfig config, IReadOnlyList<(string Path, string? Condition)> imports, string sources)
	{
		var b = Start(sources);
		b.Append("\t<PropertyGroup>\n");
		foreach (var variable in config.Variables.Where(v => !v.IsWhen))
			b.Append($"\t\t<{variable.Name}>{Escape(variable.Value!)}</{variable.Name}>\n");
		b.Append("\t</PropertyGroup>\n");
		Imports(b, imports);
		return End(b);
	}

	public static string Targets(DotnetConfig config, IReadOnlyDictionary<string, string> expandedWhen, IReadOnlyList<(string Path, string? Condition)> imports, string sources)
	{
		var b = Start(sources);
		b.Append("\t<PropertyGroup>\n");
		foreach (var variable in config.Variables.Where(v => v.IsWhen))
		{
			b.Append($"\t\t<{variable.Name}>false</{variable.Name}>\n");
			b.Append($"\t\t<{variable.Name} Condition=\"{EscapeAttribute(expandedWhen[variable.Name])}\">true</{variable.Name}>\n");
		}
		b.Append("\t</PropertyGroup>\n");
		// The compilation constants, with the expanded condition too: DefineConstants is read when compiling
		foreach (var variable in config.Variables.Where(v => v.IsWhen && v.Define is not null))
		{
			b.Append($"\t<PropertyGroup Condition=\"{EscapeAttribute(expandedWhen[variable.Name])}\">\n");
			b.Append($"\t\t<DefineConstants>$(DefineConstants);{Escape(variable.Define!)}</DefineConstants>\n");
			b.Append("\t</PropertyGroup>\n");
		}
		Imports(b, imports);
		return End(b);
	}

	// The files that dotnet.yaml imports, from the generated file's folder (_fx/); a missing file is an error of MSBuild,
	// on purpose (fx doctor dotnet reports it too)
	static void Imports(StringBuilder b, IReadOnlyList<(string Path, string? Condition)> imports)
	{
		foreach (var (path, condition) in imports)
			b.Append(condition is null
				? $"\t<Import Project=\"$(MSBuildThisFileDirectory){EscapeAttribute(path)}\" />\n"
				: $"\t<Import Project=\"$(MSBuildThisFileDirectory){EscapeAttribute(path)}\" Condition=\"{EscapeAttribute(condition)}\" />\n");
	}

	/// <param name="packages">Id, version and expanded condition, in the order to write them.</param>
	public static string Packages(IEnumerable<(string Id, string Version, string Condition)> packages, string sources)
	{
		var b = Start(sources);
		b.Append("\t<ItemGroup>\n");
		foreach (var (id, version, condition) in packages)
			b.Append($"\t\t<PackageVersion Include=\"{EscapeAttribute(id)}\" Version=\"{EscapeAttribute(version)}\" Condition=\"{EscapeAttribute(condition)}\" />\n");
		b.Append("\t</ItemGroup>\n");
		return End(b);
	}

	static StringBuilder Start(string sources) => new StringBuilder().Append(Header(sources)).Append('\n').Append("<Project>\n");

	static string End(StringBuilder b) => b.Append("</Project>\n").ToString();

	static string Escape(string value) => SecurityElement.Escape(value).Replace("&apos;", "'").Replace("&quot;", "\"");

	static string EscapeAttribute(string value) => SecurityElement.Escape(value).Replace("&apos;", "'");
}
