<Project>

	<!-- OSS -->
	<!--	 - Files -->
	<Import Project="$(MSBuildThisFileDirectory)\..\..\oss\solution\.config\Files.props" />
	<!--	 - Core -->
	<Import Project="$(Core_Frameworks_Prop)" />
	<Import Project="$(Core_Paths_Prop)" />
	<!--	 - Project -->
	<Import Project="$(Project_Default_Prop)" />


	<!-- Plus -->
	<!--	 - Files -->
	<Import Project="$(MSBuildThisFileDirectory)\..\.config\Files.props" />
	<!--	 - Core -->
	<Import Project="$(Core_Paths_Plus_Prop)" />

	<PropertyGroup>
		<FuxionToolsVersioningEnabled>false</FuxionToolsVersioningEnabled>
	</PropertyGroup>

</Project>